[package]
name = "kbt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = "0.11.1"
tui = "0.19"
crossterm = "0.25"
