name: CI

on:
  push:
    tags:
      - "*"
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: make build

      - name: Upload kbt-linux-amd
        uses: actions/upload-artifact@v3
        with:
          name: kbt
          path: target/release/kbt

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v3
        with:
          path: target/release/kbt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: kbt ${{ github.ref_name }}
          files: target/release/kbt
