name: CI

on:
  push:
    tags:
      - "*"
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run check
        run: make check

  release:
    needs: check
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Build package
        run: make build

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: kbt ${{ github.ref_name }}
          files: target/release/kbt
